#!/bin/bash
set -e

export GITHUB_TOKEN="$INPUT_GITHUB_TOKEN"
export OPENAI_API_KEY="$INPUT_OPENAI_API_KEY"
export PR_NUMBER="$INPUT_PR_NUMBER"
export NOTION_TOKEN="$INPUT_NOTION_TOKEN"
export SYSTEM_PROMPT="$INPUT_SYSTEM_PROMPT"
export LABEL="$INPUT_LABEL"

python /app/ai_pr_write.py
